// @ts-check

/**
 * Multiple sidebars so each track (Security, RTOS, CPUs, Linux) shows its own navigation.
 * Docs are mapped to a sidebar via front matter `sidebar: <name>` or by being listed below.
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  securitySidebar: [
    {type: 'doc', id: 'security/security-overview', label: 'Security overview'},
    {
      type: 'category',
      label: 'CRA (Cyber Resilience Act)',
      link: {type: 'doc', id: 'security/cra/cra-overview'},
      items: [{type: 'autogenerated', dirName: 'security/cra'}],
    },
  ],
};

export default sidebars;
